#DAY 2


In [ ]:
# BOW
''' "ai" → column 0

"love" → column 1

"loves" → column 2

"me" → column 3 '''
from sklearn.feature_extraction.text import CountVectorizer
docs=[" I love AI", "AI loves me",]
cv= CountVectorizer()
x=cv.fit_transform(docs)
print("Vocabulary (unique words):",cv.vocabulary_)
print("Document term matrix:\n",x.toarray())

Vocabulary (unique words): {'love': 1, 'ai': 0, 'loves': 2, 'me': 3}
Document term matrix:
 [[1 1 0 0]
 [1 0 1 1]]


In [ ]:
#TF-IDF
#TF-IDF(word,doc)=TF(word,doc)×log(N/df)​
#TF(word,doc)=Number of times the word appears in the document​/Total number of words in the document
#Eg:
#TF("AI", doc) = 1/3 ≈ 0.333
#TF("loves", doc) = 1/3 ≈ 0.333
#TF("me", doc) = 1/3 ≈ 0.333
from sklearn.feature_extraction.text import TfidfVectorizer
docs=[" I love AI", "AI loves me",]
tfidf=TfidfVectorizer()
x=tfidf.fit_transform(docs)
print("Vocabulary (unique words):",tfidf.vocabulary_)
print("Document term matrix:\n",x.toarray())


Vocabulary (unique words): {'love': 1, 'ai': 0, 'loves': 2, 'me': 3}
Document term matrix:
 [[0.57973867 0.81480247 0.         0.        ]
 [0.44943642 0.         0.6316672  0.6316672 ]]


In [ ]:
!pip install gensim

In [ ]:

from gensim.models import Word2Vec
sentences =[
    ["dog","bark"],
    ["cat",'meow'],
    ["dog","runs"],
    ["bird","sings"],
    ["cat","sleeps"],
    ["bird","flys"]
]
model=Word2Vec(sentences,vector_size=10,window=2,min_count=1,workers=2)
print("vector for dog",model.wv['dog'])

vector for dog [ 0.07311766  0.05070262  0.06757693  0.00762866  0.06350891 -0.03405366
 -0.00946401  0.05768573 -0.07521638 -0.03936104]


In [ ]:
import gensim.downloader as api
model=api.load("glove-wiki-gigaword-50")
similar_words=model.most_similar("cat")
print("Most similar words to 'cat :",similar_words)


[==================================================] 100.0% 66.0/66.0MB downloaded
Most similar words to 'cat : [('dog', 0.9218006134033203), ('rabbit', 0.8487821221351624), ('monkey', 0.8041081428527832), ('rat', 0.7891963124275208), ('cats', 0.7865270972251892), ('snake', 0.7798910737037659), ('dogs', 0.7795814871788025), ('pet', 0.7792249917984009), ('mouse', 0.773166835308075), ('bite', 0.7728800177574158)]


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
x=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9]])
y=np.array([0,0,0,0,1,1,1,1,1])
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
model=LogisticRegression()
print(x_train)
print(y_train)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

[[1]
 [9]
 [3]
 [5]
 [4]
 [7]]
[0 1 0 1 0 1]
1.0


In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
!pip install gensim transformers torch nltk -q
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
from transformers import BertTokenizer, BertModel
import torch
sentence1="He sat on the bank of the river."
sentences2="I deposited money in the bank."
sentences=[sentence1,sentences2]
tokenized_data=[word_tokenize(sent.lower()) for sent in sentences]
w2v_model=Word2Vec(tokenized_data,vector_size=100,window=5,min_count=1,workers=4)
print(w2v_model.wv['bank'])


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


[ 9.4563962e-05  3.0773198e-03 -6.8126451e-03 -1.3754654e-03
  7.6685809e-03  7.3464094e-03 -3.6732971e-03  2.6427018e-03
 -8.3171297e-03  6.2054861e-03 -4.6373224e-03 -3.1641065e-03
  9.3113566e-03  8.7338570e-04  7.4907029e-03 -6.0740625e-03
  5.1605068e-03  9.9228229e-03 -8.4573915e-03 -5.1356913e-03
 -7.0648370e-03 -4.8626517e-03 -3.7785638e-03 -8.5361991e-03
  7.9556061e-03 -4.8439382e-03  8.4236134e-03  5.2625705e-03
 -6.5500261e-03  3.9578713e-03  5.4701497e-03 -7.4265362e-03
 -7.4057197e-03 -2.4752307e-03 -8.6257253e-03 -1.5815723e-03
 -4.0343284e-04  3.2996845e-03  1.4418805e-03 -8.8142155e-04
 -5.5940580e-03  1.7303658e-03 -8.9737179e-04  6.7936908e-03
  3.9735902e-03  4.5294715e-03  1.4343059e-03 -2.6998555e-03
 -4.3668128e-03 -1.0320747e-03  1.4370275e-03 -2.6460087e-03
 -7.0737829e-03 -7.8053069e-03 -9.1217868e-03 -5.9351693e-03
 -1.8474245e-03 -4.3238713e-03 -6.4606704e-03 -3.7173224e-03
  4.2891586e-03 -3.7390434e-03  8.3781751e-03  1.5339935e-03
 -7.2423196e-03  9.43379

In [ ]:
from gensim.models import fasttext
sentence=[["happy","happiness","unhappy","unhappiness"]]
ft_model=fasttext.FastText(sentence,vector_size=100,window=5,min_count=1,workers=4)
print("vector for unhappiness:\n",ft_model.wv['unhappiness'])
print("Most similiar to 'unhappiness :",ft_model.wv.most_similar("unhappiness"))
print("Most similiar to 'happy :",ft_model.wv.most_similar("happy"))

vector for unhappiness:
 [-1.4853789e-03 -1.1603916e-04 -2.6417556e-04  1.1438081e-03
 -8.1752997e-04 -5.4228184e-04  1.1870451e-03  3.4255657e-04
 -8.2351820e-04  2.2573932e-04  9.8163390e-04  3.5353398e-04
  9.3867898e-04  1.2089836e-03  4.9651033e-05 -1.1284894e-03
  1.3815335e-03  6.9125171e-04  4.9050205e-04 -4.6529397e-04
  9.9748909e-04  1.5839431e-04 -1.4485023e-04  5.4476346e-04
  2.4787354e-04 -1.0724869e-03 -8.7360683e-04  1.6209706e-04
 -8.8858698e-04  3.1862097e-04 -2.3912589e-04  1.9212552e-05
 -3.4380897e-05  7.1254489e-04  1.8871486e-05  3.2873513e-04
 -1.1267792e-03  5.9013313e-05 -5.4184196e-04  8.1133458e-04
 -1.3385013e-03  9.0538560e-05 -9.3875977e-04  2.8281425e-05
 -4.4753894e-04  1.5761622e-03 -1.3700468e-03  3.4709636e-04
  3.1044416e-04  1.0422460e-03  1.8874579e-04 -1.1543221e-03
 -1.4086190e-03 -1.2028741e-03 -8.1470772e-04 -3.7127556e-04
 -7.9761801e-04 -1.5276838e-03  8.5123332e-04  1.7463227e-04
  6.3609367e-04 -9.5208018e-04  5.3143554e-04 -6.4415572e-04